services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: pgrag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres#2025
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped